[package]
name = "astarpa-c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
astarpa.workspace = true
pa-types.workspace = true
pa-heuristic.workspace = true
