[package]
name = "pairwise-aligner"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
#lto = true
lto = "thin"
incremental = true
debug = true

[dependencies]
bio-types = "*"
bio = "*"
rand = "*"
rand_chacha = "*"
# TODO: Only used for generating random sequences. Replace with own/more generic standalone implementation?
block-aligner={version="*", features=["simd_avx2"]}
csv = "*"
serde = "*"
itertools = "*"
strum_macros = "*"
termion = "*"
rustc-hash = "*"
