[package]
name = "astar-pairwise-aligner"
authors = ["Ragnar Groot Koerkamp", "Pesho Ivanov"]
description = "An exact global pairwise aligner using A* with the [chaining] seed heurstic and match pruning."
version = "0.1.0"
edition = "2021"
repository = "https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner"
license = "MPL-2.0"
keywords = ["alignment", "edit-distance", "A*", "bioinformatics", "cli"]
readme = "README.org"
categories = ["science"]
default-run = "astar-pairwise-aligner"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
#lto = true
lto = "thin"
incremental = true
debug = true
opt-level = 3

[build-dependencies]
bindgen = "0.60.1"

[dependencies]
colorgrad = "*"
bio = "*"
rand = "*"
rand_chacha = "*"
itertools = "*"
rustc-hash = "*"
clap = {version="3.*", features=["derive", "wrap_help"]}
lazy_static = "*"
smallvec = {version="*", features=["union"]}
ropey = "*"
num-traits = "*"
sdl2 = {version="*", optional=true, default_features=false}
parse_duration = "*"

[dev-dependencies]
# For benchmarking only.
aho-corasick = "*"
suffix = "*"

[features]
wfa = []
edlib = []
sdl2_ttf = ["sdl2/ttf"]
default = []
