[package]
name = "astar-pairwise-aligner"
authors = ["Ragnar Groot Koerkamp", "Pesho Ivanov"]
description = "An exact global pairwise aligner using A* with the [chaining] seed heurstic and match pruning."
version = "0.1.0"
edition = "2021"
repository = "https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner"
license = "MPL-2.0"
keywords = ["alignment", "edit-distance", "A*", "bioinformatics", "cli"]
readme = "README.org"
categories = ["science"]
default-run = "astar-pairwise-aligner"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
# 2x smaller file size when 'true', but that takes longer
lto = "thin"
incremental = true
opt-level = 3
debug = true
# 10x smaller file size without debug symbols.
# Breaks backtrace printing.
strip = false

[build-dependencies]
bindgen = "0.60.1"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
colorgrad = "*"
instant = "*"
bio = "*"
rand = "*"
rand_chacha = "*"
getrandom = "*"
itertools = "*"
rustc-hash = "*"
clap = {version="3.*", features=["derive"]}
lazy_static = "*"
smallvec = {version="*", features=["union"]}
ropey = "*"
num-traits = "*"
sdl2 = {version="*", optional=true, features=["ttf"]}
parse_duration = "*"
serde = "*"
serde_json = "*"
triple_accel = "*"
derive_more = "*"

wasm-bindgen = {version="*", optional=true}
console_error_panic_hook = {version="*", optional=true}
web-sys = { version = "*", optional=true, features = [
"ImageData",
"CanvasRenderingContext2d",
"HtmlCanvasElement",
"console",
"BinaryType", "Blob", "ErrorEvent", "MessageEvent", "ProgressEvent", "WebSocket",
"Document", "Element", "HtmlElement", "Node", "Window", "HtmlInputElement",
"HtmlSelectElement", "HtmlTextAreaElement"
]}


[[example]]
name = "fig_layers"
required-features = ["example"]


[dev-dependencies]
# For benchmarking only.
aho-corasick = "*"
suffix = "*"

[features]
default = ["bin"]

# Make some changes for example visualizations.
example = ["dep:sdl2", "sdl2"]

# Enable the visualizer using sdl2.
# TODO: Remove this and use dep:sdl2 instead
sdl2 = []

# Link third party libraries
wfa = []
edlib = []

bin = ["clap/wrap_help", "dep:sdl2", "sdl2"]
wasm = ["dep:wasm-bindgen", "dep:web-sys", "getrandom/js", "instant/wasm-bindgen", "dep:console_error_panic_hook"]
