[package]
name = "pairwise-aligner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
#lto = true
lto = "thin"
incremental = true
debug = true

[dependencies]
bio-types = "*"
bio = "*"
rand = "*"
rand_chacha = "*"
csv = "*"
serde = "*"
itertools = "*"
strum = "*"
strum_macros = "*"
termion = "*"
rustc-hash = "*"
structopt = "*"
aho-corasick = "*"
suffix = "*"
lazy_static = "*"
smallvec = {version="*", features=["union"]}
ropey = "*"
