[package]
name = "pairwise-aligner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
#lto = true
lto = "thin"
incremental = true
debug = true

[dependencies]
colorgrad = "*"
bio-types = "*"
bio = "*"
rand = "*"
rand_chacha = "*"
csv = "*"
serde = "*"
itertools = "*"
strum = "*"
strum_macros = "*"
rustc-hash = "*"
structopt = "*"
suffix = "*"
lazy_static = "*"
smallvec = {version="*", features=["union"]}
ropey = "*"
num-traits = "*"
sdl2 = {version="*", optional=true}
parse_duration = "*"
seq-macro = "*"
paste = "*"

[dev-dependencies]
# For benchmarking only.
aho-corasick = "*"

[features]
default = ["sdl2"]
