[package]
name = "astar-pairwise-aligner"
authors = ["Ragnar Groot Koerkamp", "Pesho Ivanov"]
description = "An exact global pairwise aligner using A* with the [chaining] seed heurstic and match pruning."
version = "0.1.0"
edition = "2021"
repository = "https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner"
license = "MPL-2.0"
keywords = ["alignment", "edit-distance", "A*", "bioinformatics", "cli"]
readme = "README.org"
categories = ["science"]
default-run = "astar-pairwise-aligner"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
# 2x smaller file size when 'true', but that takes longer
lto = "thin"
incremental = true
opt-level = 3
debug = true
# 10x smaller file size without debug symbols.
# Breaks backtrace printing.
strip = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
# aligners to compare against
triple_accel = { git="https://github.com/Daniel-Liu-c0deb0t/triple_accel" }

pa-generate = { git = "https://github.com/pairwise-alignment/pa-generate" }
pa-types = { git = "https://github.com/pairwise-alignment/pa-types" }

# Libs
# wasm-friendly instant
instant = "0.1.12"
bio = "1.1.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
itertools = "0.10.5"
rustc-hash = "1.1.0"
clap = { version = "4.0", features = ["derive"] }
num-traits = "0.2.15"
parse_duration = "2.1.1"
serde = "1.0.152"
derive_more = { version = "0.99.17", default-features = false, features = ["add_assign"] }
smallvec = { version = "1.10.0", features = ["union"] }



[[example]]
name = "fig_layers"
required-features = ["vis"]


[dev-dependencies]
# For benchmarking only.
aho-corasick = "*"
suffix = "*"
lazy_static = "1.4.0"

[features]
bin = ["clap/wrap_help"]
