[package]
name = "pa-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pa-types = { git = "https://github.com/pairwise-alignment/pa-types" }
pa-heuristic = { path = "../pa-heuristic" }
pa-vis-types = { path = "../pa-vis-types" }
pa-vis = { path = "../pa-vis", default-features = false }
pa-affine-types = { path = "../pa-affine-types" }
astarpa = { path = "../astarpa" }

serde_json = "1.0.91"
rand = "0.8.5"
rand_chacha = "0.3.1"
web-sys = { version = "0.3.60", features = [
"ImageData",
"CanvasRenderingContext2d",
"HtmlCanvasElement",
"console",
"BinaryType", "Blob", "ErrorEvent", "MessageEvent", "ProgressEvent", "WebSocket",
"Document", "Element", "HtmlElement", "Node", "Window", "HtmlInputElement",
"HtmlSelectElement", "HtmlTextAreaElement"
]}
console_error_panic_hook = "0.1.7"
serde = { version = "1.0.152", features = ["derive"] }
wasm-bindgen = "0.2.83"
getrandom = { version = "0.2.8", features = ["js"] }
