[package]
name = "pa-vis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sdl2 = { version = "0.35.2", features = ["ttf"], optional = true }

[features]
# Enable visualizations using sdl2.
vis = ["dep:sdl2"]

colorgrad = "0.6.2"
