[package]
name = "pa-bin"
version = "0.1.0"
edition = "2021"
default-run = "pa-bin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pa-types.workspace = true
pa-generate.workspace = true
astarpa.workspace = true

itertools.workspace = true
clap.workspace = true
pa-vis.workspace = true

[dev-dependencies]
pa-base-algos.workspace = true
pa-heuristic.workspace = true
pa-affine-types.workspace = true
rand = "0.8.5"
pa-vis-types.workspace = true
rand_chacha = "0.3.1"
bio.workspace = true

[features]
example = ["pa-heuristic/example"]

[[example]]
name = "fig_layers"
required-features = ["example"]
