name: Cargo test
on: [push, pull_request]

jobs:
  test:
    name: Cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          # Only test the astarpa package; other tests are broken.
          args: --lib --release --no-default-features --package astarpa
